### ISSUE TITLE
Songs not deleting from collection

### ISSUE THREAD

**Issue by rtluu** [openrecord/vinyl#145]
https://streamable.com/vk9l7

**Comment by jamesmcnamara** [comment]
This works fine for me. Can you send me the error logs if you can repeat this?

**Comment by rtluu** [comment]
this is the console error output associated with the bug above
<img width="1680" alt="screenshot 2018-11-19 19 20 02" src="https://user-images.githubusercontent.com/7230519/48743262-61e84f00-ec30-11e8-97aa-a4a1f6ebda89.png">
