### ISSUE TITLE
Design Homepage V2

### ISSUE THREAD

**Issue by rtluu** [openrecord/vinyl#191]
## Description
*Currently*, the homepage is just an input box for both creating & entering collections. 

*Now*, we want the homepage to be more robust with:
- [ ] Separate paths for `Creating a collection` vs. `Entering a collection`
- [ ] A section explaining OpenRecord's value to users - [see product vision/goals](https://github.com/openrecord/vinyl/tree/master/product)
- [ ] A section for `Recent Collections` so users can discover music that others are adding

## Current Screenshot 
<img width="1440" alt="screen shot 2019-02-04 at 11 31 44 pm" src="https://user-images.githubusercontent.com/7230519/52253297-13fcf200-28d5-11e9-9ab7-0ca27fd81741.png">

**Comment by Agiraldez17** [comment]
Story is ready for the first round of feedback. @rtluu See comment on figma
