### ISSUE TITLE
Organized Z-Index System

### ISSUE THREAD

**Issue by jamesmcnamara** [openrecord/vinyl#20]
We currently have `z-index`'s scattered through the app, which is a nightmare to maintain.

What we need is a centralized list of components that need `z-index` where their position in the list determines their z-index. E.G. `z-indexs = ['uniplayer', 'search-bar', 'nav-bar']` would give uniplayer z-index 0 and nav-bar z-index = 2. Then z-indexs are just looked up when they are needed, and adding an element to the list automatically shifts everything to the right index.

The only question is whether it should live in JS or in the SCSS. We can't mix and match, so all z-indexes will have to be set either with styled-components or classes.

**Comment by chasdevs** [comment]
I think I added that `base.scss` file a while ago as a central place for styling that is app-wide. z-index feels like it should remain in SCSS and not JS, so maybe that file is a good candidate?
